name: CI

on:
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy_serverless:
    name: deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

#      - name: Use Node.js nodejs14.x
#        uses: actions/setup-node@v3
#        with:
#        node-version: 14.x

      - run: node -v

      - name: run yarn
        run: yarn

#      - name: run deploy
#        run: Deploy
#          sls deploy --config serverless-aws.yml
