name: CI

on:
  push:
    branches: ['rest']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy_serverless:
    name: deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js nodejs14.x
        uses: actions/setup-node@v3
        with:
          node-version: nodejs14.x

      - name: Run yarn
        run: yarn

      - name: Run a multi-line script
        run: Deploy
          sls deploy --config serverless-aws.yml
